### ISSUE TITLE
background blur for expandable menu only works once

### ISSUE THREAD

**Issue by DiscreteConcrete** [GalileoSchool/website#25]
**Describe the bug**
background blur for expandable menu only works once

**Where is the bug? (If applicable)**
on main page

**To Reproduce**
1. Go to main page while on desktop
2. Click on hamburger button to get expanded menu
3. Click X to close the menu
4. Click hamburger button again

**Expected behavior**
Expected is that the blur happens again, but it doesn't.

**Screenshots**
<img width="1135" alt="Screenshot 2021-09-01 at 20 12 59" src="https://user-images.githubusercontent.com/4215979/131730145-af3b8006-ac04-442b-8437-602fd57cc2e6.png">

**Desktop (please complete the following information):**
 - Browser - Brave
 - Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)

**Additional context**

**Comment by AdrianJakubcik** [comment]
Very interesting I can't seem to reproduce this problem. Can you see any errors in the developer console?

**Comment by DiscreteConcrete** [comment]
Turns out it was my aggressive pop-up blocker PopUpOFF 2.0. The overlay it identified as a popup, so it blocked it. This means but some others might have a similar problem, but it's a heavy minority of users, so I'm closing the issue.
