### ISSUE TITLE
Interview overlay does not open

### ISSUE THREAD

**Issue by DiscreteConcrete** [GalileoSchool/website#31]
**Describe the bug**
Interview overlay does not open

**Where is the bug? (If applicable)**
absolventi page https://galileoschool.github.io/html/sk/interviews/index.html

**To Reproduce**
1. Go to https://galileoschool.github.io/html/sk/interviews/index.html?id=256002977
2. Click on any of the interview tiles - the URL changes, but nothing happens visually

**Expected behavior**
The interview opens.

**Screenshots**
<img width="1157" alt="Screenshot 2021-09-01 at 20 48 46" src="https://user-images.githubusercontent.com/4215979/131735186-ff96dbb0-b9f9-4ff0-84eb-bd67ba82bdb9.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser: Brave
 - Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (x86_64)

**Comment by AdrianJakubcik** [comment]
Again, I can't reproduce this problem...

![image](https://user-images.githubusercontent.com/45712887/136992949-d1a08c0b-b2ad-4588-a284-7c05621ca6b4.png)
